"""
stocks.py
---------
Master list of NSE-listed Indian stocks for the autocomplete dropdown.
Format: { "Company Name (Display)": "TICKER.NS" }
"""

STOCKS: dict[str, str] = {
    "Reliance Industries": "RELIANCE.NS",
    "Tata Consultancy Services (TCS)": "TCS.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "Infosys": "INFY.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "Hindustan Unilever (HUL)": "HINDUNILVR.NS",
    "State Bank of India (SBI)": "SBIN.NS",
    "Bharti Airtel": "BHARTIARTL.NS",
    "ITC": "ITC.NS",
    "Kotak Mahindra Bank": "KOTAKBANK.NS",
    "Larsen & Toubro (L&T)": "LT.NS",
    "Asian Paints": "ASIANPAINT.NS",
    "Axis Bank": "AXISBANK.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "Maruti Suzuki": "MARUTI.NS",
    "HCL Technologies": "HCLTECH.NS",
    "Sun Pharmaceutical": "SUNPHARMA.NS",
    "Wipro": "WIPRO.NS",
    "UltraTech Cement": "ULTRACEMCO.NS",
    "Titan Company": "TITAN.NS",
    "Nestle India": "NESTLEIND.NS",
    "Power Grid Corporation": "POWERGRID.NS",
    "NTPC": "NTPC.NS",
    "Mahindra & Mahindra (M&M)": "M&M.NS",
    "Tech Mahindra": "TECHM.NS",
    "Bajaj Auto": "BAJAJ-AUTO.NS",
    "Tata Motors": "TATAMOTORS.NS",
    "Dr. Reddy's Laboratories": "DRREDDY.NS",
    "Cipla": "CIPLA.NS",
    "Adani Ports": "ADANIPORTS.NS",
    "Adani Enterprises": "ADANIENT.NS",
    "Adani Green Energy": "ADANIGREEN.NS",
    "Adani Power": "ADANIPOWER.NS",
    "Coal India": "COALINDIA.NS",
    "ONGC": "ONGC.NS",
    "Indian Oil Corporation (IOC)": "IOC.NS",
    "Bharat Petroleum (BPCL)": "BPCL.NS",
    "Hindustan Petroleum (HPCL)": "HPCL.NS",
    "Tata Steel": "TATASTEEL.NS",
    "JSW Steel": "JSWSTEEL.NS",
    "Hindalco Industries": "HINDALCO.NS",
    "Vedanta": "VEDL.NS",
    "Grasim Industries": "GRASIM.NS",
    "Shree Cement": "SHREECEM.NS",
    "ACC": "ACC.NS",
    "Ambuja Cements": "AMBUJACEM.NS",
    "Pidilite Industries": "PIDILITIND.NS",
    "Godrej Consumer Products": "GODREJCP.NS",
    "Dabur India": "DABUR.NS",
    "Marico": "MARICO.NS",
    "Colgate-Palmolive India": "COLPAL.NS",
    "Havells India": "HAVELLS.NS",
    "Voltas": "VOLTAS.NS",
    "Crompton Greaves Consumer": "CROMPTON.NS",
    "Dixon Technologies": "DIXON.NS",
    "Tata Power": "TATAPOWER.NS",
    "Torrent Power": "TORNTPOWER.NS",
    "NHPC": "NHPC.NS",
    "Indraprastha Gas (IGL)": "IGL.NS",
    "Petronet LNG": "PETRONET.NS",
    "Gail India": "GAIL.NS",
    "Hero MotoCorp": "HEROMOTOCO.NS",
    "Eicher Motors (Royal Enfield)": "EICHERMOT.NS",
    "Bajaj Finserv": "BAJAJFINSV.NS",
    "HDFC Life Insurance": "HDFCLIFE.NS",
    "SBI Life Insurance": "SBILIFE.NS",
    "ICICI Prudential Life": "ICICIPRULI.NS",
    "LIC of India": "LICI.NS",
    "Muthoot Finance": "MUTHOOTFIN.NS",
    "Cholamandalam Finance": "CHOLAFIN.NS",
    "Shriram Finance": "SHRIRAMFIN.NS",
    "SBI Cards": "SBICARD.NS",
    "HDFC AMC": "HDFCAMC.NS",
    "Nippon India AMC (NAM India)": "NAM-INDIA.NS",
    "Divi's Laboratories": "DIVISLAB.NS",
    "Biocon": "BIOCON.NS",
    "Apollo Hospitals": "APOLLOHOSP.NS",
    "Max Healthcare": "MAXHEALTH.NS",
    "Fortis Healthcare": "FORTIS.NS",
    "Lupin": "LUPIN.NS",
    "Aurobindo Pharma": "AUROPHARMA.NS",
    "Zydus Lifesciences": "ZYDUSLIFE.NS",
    "Abbott India": "ABBOTINDIA.NS",
    "Tata Consumer Products": "TATACONSUM.NS",
    "United Spirits (Diageo India)": "UNITDSPR.NS",
    "Varun Beverages (VBL)": "VBL.NS",
    "Zomato": "ZOMATO.NS",
    "Swiggy": "SWIGGY.NS",
    "Nykaa (FSN E-Commerce)": "NYKAA.NS",
    "PB Fintech (Policybazaar)": "POLICYBZR.NS",
    "One97 Communications (Paytm)": "PAYTM.NS",
    "Delhivery": "DELHIVERY.NS",
    "InterGlobe Aviation (IndiGo)": "INDIGO.NS",
    "Indian Railway Finance (IRFC)": "IRFC.NS",
    "Rail Vikas Nigam (RVNL)": "RVNL.NS",
    "IRCTC": "IRCTC.NS",
    "Bharat Electronics (BEL)": "BEL.NS",
    "HAL (Hindustan Aeronautics)": "HAL.NS",
    "Bharat Dynamics (BDL)": "BDL.NS",
    "Mazagon Dock": "MAZDOCK.NS",
    "Tata Elxsi": "TATAELXSI.NS",
    "Persistent Systems": "PERSISTENT.NS",
    "Mphasis": "MPHASIS.NS",
    "LTIMindtree": "LTIM.NS",
    "Coforge": "COFORGE.NS",
    "Oracle Financial Services (OFSS)": "OFSS.NS",
    "Hindustan Zinc": "HINDZINC.NS",
    "National Aluminium (NALCO)": "NATIONALUM.NS",
    "NMDC": "NMDC.NS",
    "Motherson Sumi (SAMIL)": "MOTHERSON.NS",
    "Bosch India": "BOSCHLTD.NS",
    "MRF Tyres": "MRF.NS",
    "Apollo Tyres": "APOLLOTYRE.NS",
    "Page Industries (Jockey)": "PAGEIND.NS",
    "Trent (Westside / Zudio)": "TRENT.NS",
    "Avenue Supermarts (DMart)": "DMART.NS",
    "Jubilant Foodworks (Domino's)": "JUBLFOOD.NS",
    "Info Edge (Naukri / 99acres)": "NAUKRI.NS",
    "Just Dial": "JUSTDIAL.NS",
    "Indiamart Intermesh": "INDIAMART.NS",
}

SORTED_LABELS: list[str] = sorted(STOCKS.keys())
